#!/bin/bash
KC_PATH=$HOME/app/keycloak
${KC_PATH}/bin/kc.sh import --file resources/auth-server-realm.json
${KC_PATH}/bin/kc.sh start-dev --http-port 8083 --bootstrap-admin-username admin --bootstrap-admin-password pass --http-relative-path /auth &
sleep 20s
$HOME/app/vocab --httpPort 8081 --quizPath resources/vocab_quiz.csv &
java -jar $HOME/app/Callgate-0.0.1-SNAPSHOT.jar

